### ISSUE TITLE
1- crate a Projects page 

### ISSUE THREAD

**Issue by Momcil** [Momcil/capstone-pvflow#1]
## Value statement - a requirement, not a solution
As a **user (project manager)** 
I need **to see a list of  all of my Projects** 
so that **i can control the workflow** 

## Description (Text, Scribble, Wireframe, Design)
<img width="444" alt="Screenshot 2022-04-27 at 11 30 20" src="https://user-images.githubusercontent.com/81828968/165488751-04495e59-343c-4b2f-ad01-b36e643a7819.png">

## Acceptance criteria
- [x] When the frontend start the project manager should see a page with Projects list 
- [x] Project ID
- [x] Project name
- [x] Client name
- [x] names of the worker/ workers and how many hours they have worked on the project
- [x] Start Date of the project
- [x] End Date of the project
- [x] Sum of all work-hours
- [x] Status in progress / or done 

## Tasks
- [x] Create a detailed page
- [x] Render a card/s 
- [x] Create a db.js/ or an object with the data to be rendert (e.g. 
    ID: Number,
    Project name: String,
    Client name: String,
    Status: Boolean,
    Employee/Worker name: String,
    Work-hours: Number,
    Start date: Date,
    End date: Date,
    Sum of all work-hours for this project: Number
    

    

## Size
       @small

**Comment by Momcil** [comment]
that is my first issue, I will create the 2nd after the first is done  and working

**Comment by PReichetanz** [comment]
You have a nice start here!

I'd like to add which came to my mind:

- Value statement: Is the "admin / project manager" the admin of your app (with more rights than a normal user) or is the app for project managers and thus it is the main user of your app (even though he/she is manager) here you want to reach?
- For an MVP, you do not need a header with a logo; you can outsource it to another story.

## Acceptance criteria:
- the part from "Project ID" up to "status in progress / or done": You should make clear that these information need to be displayed to the user in order to get accepted.
- Where come these data from? Do you have a db.js file with hardcoded data (which would be fine for now)? Write it down here including the structure of each data object.
- Outsource the expand-button as a component to another story.
- Which part of the information are always shown and which one is additional (when the button is clicked)? Since you will not have the button in this story, display all information for now (i.e. create the "detailed card").
 
## Tasks:
   - You don't need to write down tasks like "create a new branch", "create a pull request" ... up to "close the issue".
   - Better include "Create a db.js"

**Comment by julialoeschel** [comment]
Great Job, 
I would suggest preparing the scribble according to your needs. 
You want to render a list with information, you should scribble more than one and also put real Information, to get a glimpse about size and proportions. 

other than that - good first story!!
