### ISSUE TITLE
login page

### ISSUE THREAD

**Issue by Momcil** [Momcil/capstone-pvflow#11]
## Value statement - a requirement, not a solution
As a **user** 
I need **a login page** 
so that **i can got to see all projects secure** 

## Description (Text, Scribble, Wireframe, Design)
login page 
## Acceptance criteria
- [x] input field for name type "string"
- [x] input name for password type "number"
- [ ] submit button
- [x] if the name or the password are not correct the user can't go on to the next page to see all projects
- [x] if the name or the password are correct the user can click a button to go to the next page and explore all projects

## Tasks
- [x] input for name 
- [x] input for password
- [x] button to navigate to the all projects page 
- [x] navigation between login page and all projects page
- [x] server route in server.js to get the login page 

## Size
(large)
