### ISSUE TITLE
update page

### ISSUE THREAD

**Issue by Momcil** [Momcil/capstone-pvflow#12]
## Value statement - a requirement, not a solution
As a **user** 
I need **a page** 
so that **i can update the status and the detailed information of the projects** 

## Description (Text, Scribble, Wireframe, Design)
page with input fields to update the information on project/s
## Acceptance criteria
- [x] input for project id type "number"
- [x] input for worker name type "string"
- [x] input for work hours type "number"
- [x] input for date type "date"
- [x] when the information is added clicking the submit button should insert new information to the claud 
- [x] when click the button logout the log in page should appear and the new user can sign in

## Tasks
- [x] create new mongoose model
- [x] add function in server.js to post the update information to the cloud
- [x] create new page with input fields and submit button
- [x] navigation between all projects page and update page
- [x] logout button with navigation to "/" page

## Size
(large)
