### ISSUE TITLE
2- Create a button component

### ISSUE THREAD

**Issue by Momcil** [Momcil/capstone-pvflow#3]
## Value statement - a requirement, not a solution
As a **user (project manager)** 
I need **to see detailed information of the project** 
so that **to get a better overview about the impact the project has** 

## Description (Text, Scribble, Wireframe, Design)
<img width="705" alt="Screenshot 2022-04-27 at 12 18 44" src="https://user-images.githubusercontent.com/81828968/165497093-3fdb022f-9263-4430-b1f1-ea6f9ee74da3.png">

## Acceptance criteria
- [x] When clicking the button the card should expand and detailed information are shown
   Employee Name:
   Employee Work-Hours:
   Start Date:
   End Date:
   Sum Hours:
- [x] The label of the button should change from show more to close
- [x] When the card is expanded, clicking the button should close the card and the additional information are not shown 
- [x] The label of the button should change from close to show more 

## Tasks
- [x] Create a functional button component  
- [x] Adjust Card component to display detailed information
- [x] Add story and test for Button component

## Size
small

**Comment by mbosselmann** [comment]
Hi Momchil,

I really like this user story! 👍  But I have some remarks that you should consider before going to your next user story:

Your **value statement** is good, but I would focus more on the goal and not on the solution. Because the button is how you want to solve the user's need to see more details. I would suggest something like this:

**As a** user (project manager)
**I need** to see detailed information of the project
**to be able to** get a better overview about the impact the project has

This is just a suggestion, I'm not sure for which reason the project overview is needed as I haven't worked as a project manager yet. ;)

**Acceptance criteria:**

You could also add which information should be displayed after clicking the button. :)

**Tasks:**
I think you may have more to add more tasks:
- Adjust Card component to display detailed information
- Adjust Story for Card component
- Add story and test for Button component
- Adjust tests for Card component

These are just ideas. I would always recommend to add storybook and testing as tasks so that you don't forget to write your stories and tests. :) If you do so you should also add storybook and testing as tasks to your other user stories.
