### ISSUE TITLE
create new project page

### ISSUE THREAD

**Issue by Momcil** [Momcil/capstone-pvflow#6]
## Value statement - a requirement, not a solution
As a **user** 
I need **to be able to add new project data ** 
so that **i can add new project to my project-list** 

## Description (Text, Scribble, Wireframe, Design)

<img width="656" alt="Screenshot 2022-05-05 at 12 05 41" src="https://user-images.githubusercontent.com/81828968/166903151-064ef1bb-8ca6-4181-8019-3ccb6e8dc44e.png">

## Acceptance criteria
- [x] create a form for creating new project
- [x] the form should have : 
       input: project ID " number"
       input: project name "string"
       input: client name "string"
       input: status  "string"
       input: start date "string"
       input: end date "string"
- [x] when click on the button create new project the user should see the list with all projects and the newly created project should appear in the list

## Tasks
- [x] create a form for adding new project
- [x] create navigation between projects list and create page 

## Size
 large

**Comment by julialoeschel** [comment]
Hey Momcil, 
over all a pretty good story.
I have some suggestions for you:

- Please write an Title for your story.
- The Value statement could be more precise about what page the user need (its an Input page, right? to enter data.)
- for your scribble try to use more realistic sizes. Usually an text input field expands about the screen width for example. ( for better usability)
- does "create new project" and "home" buttons lead to the same page? That´s not clear for me.
- Acceptance criteria: what kind of data do you accept here? Numbers only, max or min length of entries etc?
- I am not sure about the landing page, is it a new page? maybe this is a good 3dt user story?

**Comment by julialoeschel** [comment]
Hello Again :) 

your title is still ` (Short name) #6`  , which is not the correct name I guess :) 

"I need Page" is also not quiet descriptive. what about "as a user, I need to enter my Project Data, to be able to add new...." ? 

other than that, good Job :)

**Comment by Momcil** [comment]
i did the suggested changes, thank you for the tips!
