### ISSUE TITLE
change db.js to teal DB: MongoDB- Atlass- Cloud

### ISSUE THREAD

**Issue by Momcil** [Momcil/capstone-pvflow#8]
## Value statement - a requirement, not a solution
As a **developer** 
I need **to connect my App to a real DB** 
so that **i can test the connection and functionality of my App with a real server** 

## Description (Text, Scribble, Wireframe, Design)
- [x] connecting my App to real live server

## Acceptance criteria
- [x] fetch and render real data from server
- [x] option to create new project/s
- [x] option to delete old project/s
- [x] when a button add new project is clicked the page change to add new project and a create form is shown
- [x] when all input fields are don and the button create new project is clicked the new information should be insert to the real DB
- [x] when the clicking the button back to project the page show all projects is shown and the new project should be seen in the list

## Tasks
- [x] connect to [cloud](https://cloud.mongodb.com/)
- [x] create a server.js with functional connection
- [x] create a mongoose model
- [x] create new button to navigate back to show all projects page

## Size
(large)

**Comment by mbosselmann** [comment]
Hi Momchil,
your user story looks good! 👍 My remarks:

First point is nit-picking: You value proposition has a formatting issue ("so that **i can test the connection and functionality of my App with a real server **")

And a idea: You could think about splitting this user story in multiple user stories for better handling. One user story for create a new project, one for delete an old project for example. Maybe then it will be easier for you to implement the functionality. :)

**Comment by Momcil** [comment]
I am almost don with the issue so i don't need to split the user story :)
